dist: bionic

language: php

sudo: false

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=^6.0
    - LARAVEL=^7.0
    - LARAVEL=dev-develop

matrix:
  fast_finish: true
  exclude:
    - php: '7.1'
      env: LARAVEL=^6.0
    - php: '7.1'
      env: LARAVEL=^7.0
    - php: '7.1'
      env: LARAVEL=dev-develop
    - php: '7.2'
      env: LARAVEL=dev-develop
  allow_failures:
    - env: LARAVEL=dev-develop

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --verbose
