language: php

sudo: false

php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=5.9.*

matrix:
  fast_finish: true

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require "illuminate/framework=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit --verbose
